name: Serverless Deploy

concurrency:
  group: cd-${{ github.ref }}

on:
  push:
    branches:
      - dev
      - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.18.x]
    environment: ${{ github.ref_name }}
    env:
      STAGE: ${{ secrets.STAGE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          role-session-name: gh-actions
          aws-region: ap-southeast-1

      - name: Validate AWS Access
        run: |
          aws sts get-caller-identity

      - name: Create deployment packages
        run: |
          GOPRIVATE=github.com/SPHTech CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bin/serverless cmd/serverless/main.go
          zip -r bin/handler.zip bin
          zip -ur bin/handler.zip ./configs
      - name: Update Lambda code (shell lambda was setup using TF)
        run: |
          aws lambda update-function-code --function-name=home-feed --zip-file=fileb://bin/handler.zip
